openapi: 3.0.3
info:
  title: 'WK CRM Brasil API Documentation'
  description: ''
  version: 1.0.0
servers:
  -
    url: 'http://localhost:8001'
tags:
  -
    name: Endpoints
    description: ''
paths:
  /api/customers:
    post:
      summary: ''
      operationId: postApiCustomers
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: consequatur
                  nullable: false
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: carolyne.luettgen@example.org
                  nullable: false
                phone:
                  type: string
                  description: ''
                  example: consequatur
                  nullable: true
                status:
                  type: string
                  description: ''
                  example: consequatur
                  nullable: true
                company:
                  type: string
                  description: ''
                  example: consequatur
                  nullable: true
                address:
                  type: string
                  description: ''
                  example: consequatur
                  nullable: true
                city:
                  type: string
                  description: ''
                  example: consequatur
                  nullable: true
                state:
                  type: string
                  description: ''
                  example: consequatur
                  nullable: true
                zip_code:
                  type: string
                  description: ''
                  example: consequatur
                  nullable: true
                country:
                  type: string
                  description: ''
                  example: consequatur
                  nullable: true
              required:
                - name
                - email
      security: []
  '/api/customers/{id}':
    put:
      summary: ''
      operationId: putApiCustomersId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: consequatur
                  nullable: false
                email:
                  type: string
                  description: ''
                  example: null
                  nullable: false
                phone:
                  type: string
                  description: ''
                  example: consequatur
                  nullable: true
                status:
                  type: string
                  description: ''
                  example: consequatur
                  nullable: true
                company:
                  type: string
                  description: ''
                  example: consequatur
                  nullable: true
                address:
                  type: string
                  description: ''
                  example: consequatur
                  nullable: true
                city:
                  type: string
                  description: ''
                  example: consequatur
                  nullable: true
                state:
                  type: string
                  description: ''
                  example: consequatur
                  nullable: true
                zip_code:
                  type: string
                  description: ''
                  example: consequatur
                  nullable: true
                country:
                  type: string
                  description: ''
                  example: consequatur
                  nullable: true
              required:
                - name
      security: []
    delete:
      summary: ''
      operationId: deleteApiCustomersId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the customer.'
        example: consequatur
        required: true
        schema:
          type: string
  /api/leads:
    post:
      summary: ''
      operationId: postApiLeads
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: consequatur
                  nullable: false
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: carolyne.luettgen@example.org
                  nullable: true
                phone:
                  type: string
                  description: ''
                  example: consequatur
                  nullable: true
                status:
                  type: string
                  description: ''
                  example: consequatur
                  nullable: true
                source:
                  type: string
                  description: ''
                  example: consequatur
                  nullable: true
                company:
                  type: string
                  description: ''
                  example: consequatur
                  nullable: true
              required:
                - name
      security: []
  '/api/leads/{id}':
    put:
      summary: ''
      operationId: putApiLeadsId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  description: ''
                  example: consequatur
                  nullable: false
                email:
                  type: string
                  description: 'Must be a valid email address.'
                  example: carolyne.luettgen@example.org
                  nullable: true
                phone:
                  type: string
                  description: ''
                  example: consequatur
                  nullable: true
                status:
                  type: string
                  description: ''
                  example: consequatur
                  nullable: true
                source:
                  type: string
                  description: ''
                  example: consequatur
                  nullable: true
                company:
                  type: string
                  description: ''
                  example: consequatur
                  nullable: true
              required:
                - name
      security: []
    delete:
      summary: ''
      operationId: deleteApiLeadsId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the lead.'
        example: consequatur
        required: true
        schema:
          type: string
  /api/opportunities:
    post:
      summary: ''
      operationId: postApiOpportunities
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: ''
                  example: consequatur
                  nullable: false
                description:
                  type: string
                  description: ''
                  example: 'Dolores dolorum amet iste laborum eius est dolor.'
                  nullable: true
                value:
                  type: number
                  description: ''
                  example: 11613.31890586
                  nullable: false
                status:
                  type: string
                  description: ''
                  example: consequatur
                  nullable: true
                customer_id:
                  type: string
                  description: 'Must be a valid UUID. The <code>id</code> of an existing record in the customers table.'
                  example: 98adc52b-966d-39db-809a-55902ee7228f
                  nullable: false
              required:
                - title
                - value
                - customer_id
      security: []
  '/api/opportunities/{id}':
    put:
      summary: ''
      operationId: putApiOpportunitiesId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                title:
                  type: string
                  description: ''
                  example: consequatur
                  nullable: false
                description:
                  type: string
                  description: ''
                  example: 'Dolores dolorum amet iste laborum eius est dolor.'
                  nullable: true
                value:
                  type: number
                  description: ''
                  example: 11613.31890586
                  nullable: false
                status:
                  type: string
                  description: ''
                  example: consequatur
                  nullable: true
                customer_id:
                  type: string
                  description: 'Must be a valid UUID. The <code>id</code> of an existing record in the customers table.'
                  example: 98adc52b-966d-39db-809a-55902ee7228f
                  nullable: false
              required:
                - title
                - value
                - customer_id
      security: []
    delete:
      summary: ''
      operationId: deleteApiOpportunitiesId
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
    parameters:
      -
        in: path
        name: id
        description: 'The ID of the opportunity.'
        example: consequatur
        required: true
        schema:
          type: string
  /api/simulate-update:
    post:
      summary: ''
      operationId: postApiSimulateUpdate
      description: ''
      parameters: []
      responses: {  }
      tags:
        - Endpoints
      security: []
